id: A46641136
title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence of the
  Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:59:06.819718
  last_modified_at: 2022-03-01 00:59:06.819745
